# Константы для моделей приложения user

USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
PASSWORD_MAX_LENGTH = 150

# Константы для моделей приложения recipes

RECIPE_NAME_MAX_LENGTH = 200
COOKING_TIME_MIN = 1
TAG_NAME_MAX_LEGTH = 200
TAG_COLOR_MAX_LEGTH = 7
TAG_SLUG_MAX_LEGTH = 200
INGREDIENT_NAME_MAX_LEGTH = 200
INGREDIENT_MEASURE_MAX_LEGTH = 200
